### ISSUE TITLE
Images in covid class are not NxN in dimensions

### ISSUE THREAD

**Issue by Electro1111** [lindawangg/COVID-Net#100]
I've noticed that most of the images in the COVID class are not square in dimensions but many of the images in the other two classes are square in dimension. How is this problem circumvented in the training process?

**Comment by haydengunraj** [comment]
Before being passed to the models, images are resized to a uniform square shape.

**Comment by Electro1111** [comment]
are the covid images distorted from their original dimensions or is it
filled in with black pixels

**Comment by haydengunraj** [comment]
No distortion occurs since images are center-cropped to a square region before resizing. See [this function](https://github.com/lindawangg/COVID-Net/blob/bb90283d696db1712debb21840ab6c2cd484400c/data.py#L20) for more details on the exact processing steps.

**Comment by Electro1111** [comment]
Ahh ok. I noticed it also removes a % from the top of the image as well.
What is the motivation here?

**Comment by haydengunraj** [comment]
My understanding is that this part of the image usually contains the head/neck/shoulders, and so it is not important for classification. The removal of the top helps center the lungs in the image so that center cropping is effective.
