### ISSUE TITLE
Missing metadata file

### ISSUE THREAD

**Issue by daquang** [lindawangg/COVID-Net#112]
Cannot find the file ./COVID-19-Radiography-Database/COVID-19.metadata.xlsx

Can you please provide the file?

**Comment by Guangyu0503** [comment]
I have the same issue too. 

Could anyone let us know where the file COVID-19-Radiography-Database/COVID-19.metadata.xlsx is? 

Many thanks

**Comment by irshadarif** [comment]
[COVID-19.metadata.xlsx](https://github.com/lindawangg/COVID-Net/files/5777144/COVID-19.metadata.xlsx)

**Comment by calzoom** [comment]
The new Covidx7 dataset contains updated scripts and links which do not have missing files
