### ISSUE TITLE
rsna_test_patients_normal.npy

### ISSUE THREAD

**Issue by irshadarif** [lindawangg/COVID-Net#118]
Where is this file or how to separate normal and pneumonia images in rsna data set. 
I'm confused,   [https://github.com/lindawangg/COVID-Net/blob/03bf7258c5d695916932078cdd54d164cac3e741/create_COVIDx.ipynb](), in dcm file reading section from rsna dataset. In dcm file reading section how they decide or where is the file, rsna_test_patients_normal.npy.

**Comment by spohngellert-o** [comment]
Hi, how did you resolve this issue? I am having the same issue.

**Comment by RuixuanDSBA** [comment]
https://github.com/lindawangg/COVID-Net/issues/130
