### ISSUE TITLE
COVIDNet-CXR model on COVIDx V7B (binary classification)

### ISSUE THREAD

**Issue by homerdiaz** [lindawangg/COVID-Net#132]
Which COVIDNet-CXR model i can use for binary classification?

**Comment by chododom** [comment]
I believe any of them can be used for binary classification, just use the inference_pneumonia.py file, which takes the max probability out of non-COVID pneumonia and COVID pneumonia. I have been using the COVIDNet-CXR-A for my binary classification.

**Comment by homerdiaz** [comment]
Hi chododom. I think that's for pneumonia binary classification. They realeased last month a new dataset for binary classification Covid positive/negative.
