### ISSUE TITLE
Getting this issue while creating covidx

### ISSUE THREAD

**Issue by khanbhai0078** [lindawangg/COVID-Net#133]
Getting issue while creating the covidx dataset using the given files.

IndexError                                Traceback (most recent call last)
<ipython-input-7-fe1cac07ee1a> in <module>
     49         imagename = patientid + '.' + row['FORMAT'].lower()
     50         if not os.path.exists(os.path.join(sirm_imgpath, imagename)):
---> 51             imagename = patientid.split('(')[0] + ' ('+ patientid.split('(')[1] + '.' + row['FORMAT'].lower()
     52         entry = [patientid, imagename, mapping['COVID-19'], 'sirm']
     53         filename_label[mapping['COVID-19']].append(entry)

IndexError: list index out of range

**Comment by haydengunraj** [comment]
Closing this, as it seems you're now using a more recent version of the dataset where this problem no longer exists. Feel free to reopen if this is not the case.
