### ISSUE TITLE
Not able to train a new model with a generated dataset with train_tf.py

### ISSUE THREAD

**Issue by kapilb7** [lindawangg/COVID-Net#135]
This is what I'm getting:

Output: /Users/kapil/Documents/COVIDNet-CXRCOVIDNet-lr0.0002
Traceback (most recent call last):
  File "train_tf.py", line 78, in <module>
    generator = BalanceCovidDataset(data_dir=args['datadir'],
  File "/Users/kapil/Documents/COVID-Net/Multi-class Classification/data.py", line 120, in __init__
    datasets[l.split()[2]].append(l)
KeyError: 'COVID(1).png'
(base) kapil@Kapils-MacBook-Pro Multi-class Classification %

**Comment by haydengunraj** [comment]
This is due to a consistency issue in our label files, which we're working to fix at the moment.
