### ISSUE TITLE
An error occurred when using eval.py

### ISSUE THREAD

**Issue by huang1030** [lindawangg/COVID-Net#139]
When I use ev.py, 
tf.train. Import_Meta_Graph (os.path.join(args.weightSpath, args.metaname)), 
I get the error：
KeyError: 'fusedBatchNormv3'
Looking forward to your reply.

**Comment by haydengunraj** [comment]
Which version of TensorFlow are you using?

**Comment by huang1030** [comment]
Thank you, I'm using Tensorflow1.13.1

**Comment by haydengunraj** [comment]
In that case, I strongly suspect that it's a version mismatch. The COVID-Net models were built using TensorFlow 1.15, and I believe that the error appears because FusedBatchNormV3 does not exist in TensorFlow 1.13.1. Upgrading to TensorFlow 1.15 should resolve the issue.

**Comment by huang1030** [comment]
> 在那种情况下，我强烈怀疑这是版本不匹配。COVID-Net模型是使用TensorFlow 1.15构建的，并且我相信出现此错误是因为TensorFlow 1.13.1中不存在FusedBatchNormV3。升级到TensorFlow 1.15应该可以解决该问题。

Thank

**Comment by huang1030** [comment]
Thanks for your advice, it has been successfully run
