### ISSUE TITLE
Not able to generate COVIDx V8 dataset

### ISSUE THREAD

**Issue by guipaiva** [lindawangg/COVID-Net#148]
Cannot proceed with [step 3](https://github.com/lindawangg/COVID-Net/blob/master/docs/COVIDx.md) to generate COVIDx V8 dataset due to a missing file and no further instructions are provided. 

When I run the script, it gives me the error: 

```
Traceback (most recent call last):
  File "create_ricord_dataset.py", line 71, in <module>
    ricord_dict = make_ricord_dict(ricord_set_file)
  File "create_ricord_dataset.py", line 34, in make_ricord_dict
    with open(ricord_data_set_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ricord_data_set.txt'
```
Instructions on script mentions 
>ricord_data_set.txt contains the name of usable images along with bounding box dimensions if needed

but neither the file or instructions to make the file were provided. 

Let me know if there is some way to proceed with the script without specifying bounding boxes.

**Comment by haydengunraj** [comment]
`ricord_data_set.txt` is provided, and can be found [here](https://github.com/lindawangg/COVID-Net/blob/master/create_ricord_dataset/ricord_data_set.txt).

**Comment by guipaiva** [comment]
Thanks. Please update the instructions with the `ricord_data_set.txt` file.
