### ISSUE TITLE
Direct link to RSNA dataset

### ISSUE THREAD

**Issue by alext234** [lindawangg/COVID-Net#15]
Just to confirm if the dataset can be downloaded directly from here as well? 

https://www.rsna.org/en/education/ai-resources-and-training/ai-image-challenge/RSNA-Pneumonia-Detection-Challenge-2018

This is to avoid the signing up a Kaggle account with mobile number confirmation.

**Comment by lindawangg** [comment]
Should be this one: [Download images from NIH chest x-ray dataset used in the Pneumonia Challenge](https://s3.amazonaws.com/east1.public.rsna.org/AI/2018/pneumonia-challenge-dataset-adjudicated-kaggle_2018.zip). The test/train split are by patient numbers so should be able to pick out the right images.
