### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by khanbhai0078** [lindawangg/COVID-Net#155]
@LindenY Kindly help
def crop_top(img, percent=0.15):
    offset = int(img.shape[0] * percent)
    return img[offset:]

def central_crop(img):
    size = min(img.shape[0], img.shape[1])
    offset_h = int((img.shape[0] - size) / 2)
    offset_w = int((img.shape[1] - size) / 2)
    return img[offset_h:offset_h + size, offset_w:offset_w + size]

def process_image_file(filepath, top_percent, size):
    img = cv2.imread(filepath)
    img = crop_top(img, percent=top_percent)
    img = central_crop(img)
    img = cv2.resize(img, (size, size))
    return img

### ERROR

  File "C:\Users\KB\Desktop\COVID-Net-master\data.py", line 15, in crop_top
    offset = int(img.shape[0] * percent)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by mayaliliya** [comment]
Hi @khanbhai0078,
This error occurs when the image is not found at the passed-in file path. Please verify that the passed-in data directory is correct and that the image file path is correct (this can be done by printing out the file path passed into the function process_image_file()).

**Comment by haydengunraj** [comment]
@khanbhai0078 , this may also be related to #158 , and so if you're using Version 4 of the COVID-19 Radiography Database please try using [Version 3](https://www.kaggle.com/tawsifurrahman/covid19-radiography-database/version/3).

If you were already using Version 3, please let us know so we can dig a bit deeper.

**Comment by khanbhai0078** [comment]
Let me try with version 3
