### ISSUE TITLE
The documentation of the creation of COVIDx8 is missing the ricord_data_set.txt file.

### ISSUE THREAD

**Issue by chododom** [lindawangg/COVID-Net#157]

**Comment by haydengunraj** [comment]
Hi Dominik,

The `ricord_data_set.txt` file can be found [here](https://github.com/lindawangg/COVID-Net/blob/master/create_ricord_dataset/ricord_data_set.txt) inside the `create_ricord_dataset` folder.

**Comment by chododom** [comment]
Thank you for the heads up, my bad :)
