### ISSUE TITLE
New COVIDx8B dataset is created in a way where files like COVID(1).png or COVID(2).png are in the labels file, but not in the actual data.

### ISSUE THREAD

**Issue by chododom** [lindawangg/COVID-Net#158]
It seems that the real name of file COVID(1).png is COVID-1.png and analogously for the others.

**Comment by chododom** [comment]
I have solved this by renaming the files in my scripts followingly:


```
labels_file = open(labels_file_path, 'r')
while True:
    line = labels_file.readLine()
    if not line:
        break
    split = line.split(' ')
    if split[-3].startswith('COVID(')
        name = split[-3].replace('(', '-')
        corrected_filename = name.replace(')', '')
```

**Comment by chododom** [comment]
Ohh okay, thank you @mayaliliya , maybe it would be good to include this in the guide to setting up the dataset, cloning the repo gets the latest version :)

**Comment by khanbhai0078** [comment]
In what place you have added this code?
