### ISSUE TITLE
why are the COVID test images in test_COVIDx8A.txt all from ricord data set?

### ISSUE THREAD

**Issue by Electro1111** [lindawangg/COVID-Net#159]
all the "covid" class images in the 8A test file are from the ricord dataset. in previous iterations of the covidx dataset (covidx7 and lower) the test set contained images from various sources. What inspired this change for the test set to only contain images from one source?

**Comment by haydengunraj** [comment]
Pinging @mayaliliya for this one, as she would have more information about the current models.

**Comment by mayaliliya** [comment]
Hi @Electro1111, 
For COVIDx8 we decided to only use CXR normal, pneumonia, and COVID-19 images curated by the Radiological Society of North America (RSNA) to ensure accurate annotations and results, and the RICORD dataset is curated by the RSNA.
