### ISSUE TITLE
Normal, Pneumonia and Covid-19 split

### ISSUE THREAD

**Issue by Khalizo** [lindawangg/COVID-Net#16]
Dear Linda,

For training the model, is there a script available that can separate the classes ( Normal, Pneumonia and Covid-19) based on the train and test text files? 

I've managed to build the train and test data sets but they aren't labeled at the moment. 

Thanks,
Babs

**Comment by lindawangg** [comment]
The provided train_COVIDx.txt and test_COVIDx.txt files are labeled. Each line contains the patientId, image name and label (normal, pneumonia and covid-19), all separated by space.
Here is a sample of how to load in there data:
```
mapping = {'normal': 0, 'pneumonia': 1, 'COVID-19': 2}
file = open('train_COVIDx.txt', 'r')
trainfiles = file.readlines()
for line in trainfiles:
    sample = line.split()
    x = cv2.imread(os.path.join('data/train', sample[1]))
    x = cv2.resize(x, self.input_shape)
    x = x.astype('float32') / 255.0
    y = mapping[sample[2]]
```

**Comment by Khalizo** [comment]
Thank you Linda for your swift response, will give it a shot!

**Comment by PaulMcInnis** [comment]
The provided script should suffice for reading the split. 

If you wish to create a new split this can easily be done with `numpy` random sampling, so long as your output is two `.txt` files in the aforementioned format.
