### ISSUE TITLE
Add compability with SIRM database v4

### ISSUE THREAD

**Issue by guipaiva** [lindawangg/COVID-Net#161]
SIRM database was updated to [version 4](https://www.kaggle.com/tawsifurrahman/covid19-radiography-database/version/4) about a month ago with over 3600 COVID-19 Chest X-ray images. It would be suitable to update the dataset generation scripts in a way that is compatible with the images from SIRM v4.

**Comment by haydengunraj** [comment]
Hi Guilherme,

This is something we may do in the future, but for now we're sticking with version 3 of the SIRM database. The main reason for this is that the numbering of the image files does not match between the two versions, and so we want to make sure that we're not accidentally mixing patients between the training and test sets.
