### ISSUE TITLE
Cannot download version 1 of the dataset COVID-19 Radiography Database

### ISSUE THREAD

**Issue by GliozzoJ** [lindawangg/COVID-Net#165]
Hello,

I am trying to use the model COVIDNet-CXR3-B (which from the performance metrics seems the one you published in your work https://www.nature.com/articles/s41598-020-76550-z ).
To this end, I need to generate the corresponding **dataset  COVIDx3**.  Following the steps to generate the dataset, I am trying to download the **Version 1 of the COVID-19 Radiography database** since the dataset is older than COVIDx6.
However, I am not able to download the COVID-19 Radiography database Version 1. I tried:

1) kaggle API, but it seems to not support the download of older versions
2) Download from the kaggle webpage (https://www.kaggle.com/tawsifurrahman/covid19-radiography-database/version/1), but I get the error "404 We can't find that page"
3) I looked for a Google Drive repository for the data, but it seems to be available only for Versions 3 and 4

Am I missing something? Do you know a way to download Version 1 of the COVID-19 Radiography database from kaggle?

All the best,
Jessica

**Comment by mayaliliya** [comment]
Hi @GliozzoJ,

Thank you for reaching out! 
Unfortunately, we do not manage that Kaggle webpage only leverage the dataset. Based on past comments and personal experience, there is no easy way to download Version 1 of the dataset only Version 3 & 4, in the past people have downloaded it image by image but that can be very tedious. I would suggest looking into using that model with the latest COVIDx8A dataset.

Hope that helps!

**Comment by guipaiva** [comment]
Hello. I'm unable to download version 3 of the Kaggle dataset which is required to create the COVIDx8 dataset. Do you have any alternative links? 

Thanks in advance.

**Comment by GliozzoJ** [comment]
Hi @mayaliliya,

thank you for your answer. I managed to download the dataset in a slightly easier way.
Instead of download image by image, I followed this steps:

1) Go to Version 1 of the COVID-19 Radiography database [(link)](https://www.kaggle.com/tawsifurrahman/covid19-radiography-database/version/1);
2) Go to the folder "COVID-19" and open it;
3) Use the option "Load more" in the bottom part of the page to visualize all the 219 images present;
4) The right-click --> save as 

In this way you can download all the images together. 
Please, pay attention to the images names because they are not consistent:
required format is COVID-19(XX).png but in the downloaded images there are some additional spaces. 
I used the bash command "rename" (Ubuntu OS) to remove unwanted spaces.
The metadata file can be downloaded [here](https://github.com/lindawangg/COVID-Net/issues/112#issuecomment-755435313).

I hope this helps other users :)

**Comment by GliozzoJ** [comment]
> Hello. I'm unable to download version 3 of the Kaggle dataset which is required to create the COVIDx8 dataset. Do you have any alternative links?
> 
> Thanks in advance.

Hi guipalva,

there is a link to a Google Drive folder with the data in the kaggle page for version 3 of the COVID-19 Radiography database.
You can find the link in the "Description" section of the kaggle page.
I report the link: https://drive.google.com/file/d/1xt7g5LkZuX09e1a8rK9sRXIrGFN6rjzl/view

All the best,
Jessica

**Comment by guipaiva** [comment]
> Hi @mayaliliya,
> 
> thank you for your answer. I managed to download the dataset in a slightly easier way.
> Instead of download image by image, I followed this steps:
> 
>     1. Go to Version 1 of the COVID-19 Radiography database [(link)](https://www.kaggle.com/tawsifurrahman/covid19-radiography-database/version/1);
> 
>     2. Go to the folder "COVID-19" and open it;
> 
>     3. Use the option "Load more" in the bottom part of the page to visualize all the 219 images present;
> 
>     4. Then right-click --> save as
> 
> 
> In this way you can download all the images together.
> Please, pay attention to the images names because they are not consistent:
> required format is COVID-19(XX).png but in the downloaded images there are some additional spaces.
> I used the bash command "rename" (Ubuntu OS) to remove unwanted spaces.
> The metadata file can be downloaded [here](https://github.com/lindawangg/COVID-Net/issues/112#issuecomment-755435313).
> 
> I hope this helps other users :)

Hi Jessica. 

Thank you for providing this method, but I can't reproduce step 4 to download all images together. Could you give more information? 

Best regards, 
Guilherme
