### ISSUE TITLE
requirement.txt is not satisfied

### ISSUE THREAD

**Issue by datonefaridze** [lindawangg/COVID-Net#174]
# Issue Template
Before posting, have you looked at the [FAQ](../docs/FAQ.md) page?

## Description

Please include a summary of the issue.
Please include the steps to reproduce.
List any additional libraries that are affected.

## Steps to Reproduce

1. First step
2. Second step
3. Third step

## Expected behavior

A description of what you expected to happen.

## Actual behavior

A description of what happens instead.

## Environment

* Build: [e.g. 3180 - type "About" in the Command Palette]
* Operating system and version: [e.g. macOS 10.14, Windows 10, Ubuntu 18.04]
* [Linux] Desktop Environment and/or Window Manager: [e.g. Gnome, LXDE, i3]
* 
hello, i am trying to install required packages but unfortunately i didn't manage to do it. i run : pip install -r requirements.txt. i run it on windows 10, it had conflicts and gave me error: summery of error was that it couldn't find compatible packages. then i used WSL ubuntu 18.0 but this didn't find compatible packages to install.

**Comment by haydengunraj** [comment]
Hi @datonefaridze ,

I believe our current requirements.txt is not minimal and may have issues - I also get an error running `pip install -r requirements.txt`. We'll hopefully update to fix this soon, but in the meantime try replacing requirements.txt with the following:

```
dicom2nifti==2.2.12
jupyter==1.0.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
matplotlib==3.2.1
nibabel==3.0.2
numpy==1.18.2
opencv-python==4.2.0.34
pandas==1.1.3
Pillow==7.1.2
pydicom==2.1.2
scikit-image==0.17.2
scikit-learn==0.22.2.post1
scipy==1.4.1
tensorboard==1.15.0
tensorflow-estimator==1.15.1
tensorflow-gpu==1.15.0
tqdm==4.46.0
```

I _think_ this represents all the requirements, but let me know if this is not the case.
