### ISSUE TITLE
Test size too small for COVID-19 cases

### ISSUE THREAD

**Issue by sreakdgeek** [lindawangg/COVID-Net#18]
With only 10 samples for COVID-19 cases, isn't the test set size too small to have any degree of confidence?

**Comment by lindawangg** [comment]
Hi,
There are only 76 COVID-19 PA samples in the chest xray dataset. We split at the patient level and got 10 samples for test, which is already more than 10% of the COVID-19 samples. As the number of COVID-19 samples continues to grow, we will update the dataset. We are not claiming any degree of confidence, nor should these model be use for production.

**Comment by sreakdgeek** [comment]
Thanks a lot for the response. Hoping that more data becomes available. Will also contribute to the data set if I am able to get access.

**Comment by ashcrok** [comment]
The source dataset that is being used by this repo has been updated. They now provide 99 COVID-19 PA samples.
