### ISSUE TITLE
Incorrect reference in white paper

### ISSUE THREAD

**Issue by ashcrok** [lindawangg/COVID-Net#19]
There is an error in the white paper on the last reference point, where the Kaggle dataset link is pointing to Cohen's dataset on github.

![image](https://user-images.githubusercontent.com/6136342/77913764-83822d80-729d-11ea-93b1-1a21a7364fea.png)

**Comment by lindawangg** [comment]
Hi,
We updated the paper. If you look at the [updated paper](https://github.com/lindawangg/COVID-Net/blob/master/assets/COVID_Netv2.pdf), you can see that the references have been changed. The updated paper has already been submitted to Arxiv.
