### ISSUE TITLE
COVIDx9A training labels include "COVID-19" and "positive"

### ISSUE THREAD

**Issue by EthanWaite** [lindawangg/COVID-Net#209]
# Issue Template
- [x] Before posting, have you looked at the [FAQ](../docs/FAQ.md) page?

## Description

The file [train_COVIDx9A.txt](https://raw.githubusercontent.com/lindawangg/COVID-Net/master/labels/train_COVIDx9A.txt) contains data with the classes `COVID-19`, `pneumonia`, and `normal`.

However, the samples from `sirm` are instead labelled `positive`. Could this be a mistake, i.e. is `COVID-19 == positive`, or is there a difference between these?

## Steps to Reproduce

```bash
$ curl https://raw.githubusercontent.com/lindawangg/COVID-Net/master/labels/train_COVIDx9A.txt -o train_COVIDx9A.txt
$ grep COVID-19 train_COVIDx9A.txt | wc -l
   15547
$ grep positive train_COVIDx9A.txt | wc -l
     943
```

**Comment by haydengunraj** [comment]
I suspect this was an oversight on our end, but @mayaliliya can confirm.

**Comment by mayaliliya** [comment]
Yes this is an oversight that must have translated from the VB train file, thank you for bringing it to our attention!
Pull request submitted from our end for review: https://github.com/lindawangg/COVID-Net/pull/215

**Comment by EthanWaite** [comment]
Thanks!
