### ISSUE TITLE
inference on cpu vs gpu

### ISSUE THREAD

**Issue by alext234** [lindawangg/COVID-Net#24]
What's the recommended environment for inference? CPU or GPU?

I've tested this on Google Colab

```
python inference.py --weightspath ./ --metaname model.meta_eval --ckptname model-6207 --imagepath assets/ex-covid.jpeg
```

With CPU it takes ~ `4.9s` 

With GPU it takes ~ `6.5s`

**Comment by DoctorDavidWalker** [comment]
After this coming Wednesday 8th April 2020 Webinar sponsored by Darwin AI, I will post benchmarking results from a diverse array of hardware and virtual machine configurations instances including all flash NVME-oF computational storage fabric, ASW and Google Cloud VMs and basic desktop endpoint hardware.  Can't wait to see my 7nm AMD EPYC CPUs and 7nm AMD GPUs with GDDR6 High Bandwidth Memory hardware and computational storage fabric run your inferences Dr. Alex.

**Comment by qodrinzo** [comment]
Hello @DoctorDavidWalker, what is the recommended system based on your benchmarking results? On my Ubuntu VPS, the inference.py raises "Killed" because of seemingly out-of-memory: #108
