### ISSUE TITLE
Can you provide pretrained model on imageNet?

### ISSUE THREAD

**Issue by Kyfafyd** [lindawangg/COVID-Net#27]
# Issue Template

## Description

Please include a summary of the issue.
Please include the steps to reproduce.
List any additional libraries that are affected.

## Steps to Reproduce

1. First step
2. Second step
3. Third step

## Expected behavior

A description of what you expected to happen.

## Actual behavior

A description of what happens instead.

## Environment

* Build: [e.g. 3180 - type "About" in the Command Palette]
* Operating system and version: [e.g. macOS 10.14, Windows 10, Ubuntu 18.04]
* [Linux] Desktop Environment and/or Window Manager: [e.g. Gnome, LXDE, i3]

**Comment by zeeshannisar** [comment]
Dear @Kyfafyd if you are asking for Pre-trained models used for detecting and visualizing the COVID-19 you can refer to my [GitHub Reposiotory](https://github.com/zeeshannisar/COVID-19) where I used three different Pre-trained Networks (VGG16, VGG19, and DenseNet121) for COVID-19 identification for the same data provided by the authors of COVID-Net. I hope it would help you for what you are asking for.

**Comment by AasiaRehman** [comment]
What is this error about??
 img = cv2.resize(img, INPUT_SIZE) # resize
cv2.error: OpenCV(3.4.2) C:\Miniconda3\conda-bld\opencv-suite_1534379934306\work\modules\imgproc\src\resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'cv::r

**Comment by zeeshannisar** [comment]
@AasiaRehman can you please share the complete code for which you are having an error?

**Comment by Kyfafyd** [comment]
@lindawangg Can you please provide the pretrained model on ImageNet?
Thanks a lod!
