### ISSUE TITLE
Dataset RSNA Pneumonia Challenge

### ISSUE THREAD

**Issue by LuigiRussoDev** [lindawangg/COVID-Net#28]
Hi to everyone, 

I've a doubt about Dataset RSNA Pneumonia Challenge. 
I'm going to download dataset (4gb) for detection of pneumonia on my own NN model. 
I was wondering if the dataset was paid or if there is any constraint over the term "challenge"

**Comment by arf111** [comment]
I'm also having trouble downloading the dataset after agreeing to the challenge rules. Also when I tried to download using `kaggle competitions download -c rsna-pneumonia-detection-challenge` I get only 6 Mb of the original dataset (instead of 4GB) where many files are missing.

**Comment by PaulMcInnis** [comment]
If you are having trouble downloading the dataset please make an issue on kaggle not here.
