### ISSUE TITLE
DataLossError While Loading Model

### ISSUE THREAD

**Issue by miracatici** [lindawangg/COVID-Net#29]
# Issue
DataLossError While Loading Model

## Environment
* Libraries
    opencv-contrib-python  4.2.0.34    
    tensorflow-gpu         1.15.0      
* Docker Environment, Tensorflow-GPU Image
* JupyterLab 2.0.1

## Description
Hi, while I'm trying to load model for inference or evaluation in jupyter, I always got this error.

```
DataLossError: Checksum does not match: stored 1497157360 vs. calculated on the restored bytes 2410561084
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```
My full notebook is shown below

```
import numpy as np
import os, argparse
import cv2
import tensorflow as tf
```
```
weightspath = '/tf/notebooks/mrc_is_here/COVID-Net/models/covid-net-large'
metaname = "model.meta_eval"
ckptname = "model-2069"
imagepath = 'assets/ex-covid.jpeg'

mapping = {'normal': 0, 'pneumonia': 1, 'COVID-19': 2}
inv_mapping = {0: 'normal', 1: 'pneumonia', 2: 'COVID-19'}
```
```
sess = tf.Session()
tf.get_default_graph()
saver = tf.train.import_meta_graph(os.path.join(weightspath, metaname))
saver.restore(sess, os.path.join(weightspath, ckptname))
```
My folder structure is:

COVID-NET
  - inference.ipynb
  - models
      - covid-net-large
          - checkpoint
          - model-2069.data-00000-of-00001
          - model-2069.index
          - mode.meta_eval
          - mode.meta_train
      - covid-net-small
          - checkpoint
          - model-6207.data-00000-of-00001
          - model-6207.index
          - mode.meta_eval
          - mode.meta_train

## Steps to Reproduce

1. Create a model folder as shown above
2. Copy all the code to a new jupyter notebook
3. Run step by step

## Expected behavior

Restore model from meta and checkpoint files

## Actual behavior

Throw exception DataLossError

**Comment by lindawangg** [comment]
This usually means that one of the model files got corrupted when downloading. Try downloading again.  You can also try to use `model.meta_train`.
