### ISSUE TITLE
Code for the model

### ISSUE THREAD

**Issue by arijitthegame** [lindawangg/COVID-Net#3]
Hi, 

 Will you be publishing the code for the model anytime soon? Thanks. 

 Best, 

 Arijit.

**Comment by lindawangg** [comment]
In our paper we outlined the architecture. We won't be releasing the code for the model since it was built using a proprietary software, GenSynth, but we just released the new model along with the evaluation script to load in the model. We are also preparing a training script to load the pretrained model for training.

**Comment by bfreskura** [comment]
@arijitthegame We have released a Pytorch model that was trained on this dataset. The architecture is not the same as the COVID-Net, but it achieves comparable performance and the model code is available. 

Hope you find it useful!
https://github.com/velebit-ai/COVID-Next-Pytorch

**Comment by arijitthegame** [comment]
Excellent. Awesome. Thank you so much.

**Comment by mfernezir** [comment]
@lindawangg For this project to be truly called open source, the exact details of the model would be most helpful to the research community.

The lack of detail hinders exact re-implementation in other frameworks, e.g. in PyTorch. It also prevents direct A/B testing of what would happen if some of the design choices were slightly altered, and this is what moves research forward.

It helps to be able to load the weights and to run inference or to continue training, but that doesn't solve the research issues mentioned above.

If you could provide your Keras or pure TF model re-implementation without any proprietary software, that would be extremely beneficial to all involved.

Thanks for your efforts!
