### ISSUE TITLE
PDF says softmax 4 but create_COVIDx_v2.ipynb only creates 3 categories.

### ISSUE THREAD

**Issue by justinmulli** [lindawangg/COVID-Net#31]
Apparently the model uses 4 softmax layers, but the latest dataset creation notebook only splits the cases into Normal, Pneumonia and Covid-19. There seems to be a mismatch here. What is the latest approach?

**Comment by lindawangg** [comment]
This is an error. Softmax should be 3 classes. Thanks for pointing it out.
