### ISSUE TITLE
Out-of-Sample filtering and transformation

### ISSUE THREAD

**Issue by cmateutss** [lindawangg/COVID-Net#32]
Hello, and thank you for sharing this great project. 

I am testing the net on out-of-sample data, some known COVID or non-COVID images and having some troubles. These are my questions to the community if anybody could help:

- Is it mandatory to filter the out-of-sample images to PA projections? Don't know if it is important or it supposed to work fine with AP too.

- Is it needed to transform the image to RGB? On the README says the Net is expecting a 224,244,3 array and DICOM images are just grayscale, i'm trying with openCV libraries transformation, don't know if this is correct to handle DICOM files:
"img=cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)"

**Comment by jamesrenhoulee** [comment]
I believe by default cv2.imread() without specifying a flag will automatically load it as a 3-channel colour image, even if you are loading in a grayscale image. Each channel in the image will just be a copy of the grayscale image.

**Comment by cmateutss** [comment]
> I believe by default cv2.imread() without specifying a flag will automatically load it as a 3-channel colour image, even if you are loading in a grayscale image. Each channel in the image will just be a copy of the grayscale image.

Yes, now I see you are right. Thank you for your reply!
