### ISSUE TITLE
Issue related to Confidence score in Inference.py

### ISSUE THREAD

**Issue by sanjaykhobragade** [lindawangg/COVID-Net#34]
The below recent commit in Inference.py file is missing "Covid-19". "Normal" is showing twice.

print('Confidence')
print('Normal: {:.3f}, Pneumonia: {:.3f}, Normal: {:.3f}'.format(pred[0][0], pred[0][1], pred[0][2]))

**Comment by lindawangg** [comment]
Fixed.
