### ISSUE TITLE
At least two variables have the same name: conv1_conv/bias

### ISSUE THREAD

**Issue by ankitdata** [lindawangg/COVID-Net#37]
Hi,
I am getting below error message frequently 
"At least two variables have the same name: conv1_conv/bias" 
when was trying to test pneumonia image and also i saw this error with normal and COVID-19 image but less frequently

version of tensor flow i have.
tensorboard = 1.14.0 
tensorflow = 1.14.0

**Comment by sfleisch** [comment]
Insert:
tensorflow.python.framework.ops.reset_default_graph()
Before our session. That occurs the second time you import the graph.

**Comment by ankitdata** [comment]
Thanks @sfleisch for quick response.
