### ISSUE TITLE
Information regarding GSInquire

### ISSUE THREAD

**Issue by paras-jain** [lindawangg/COVID-Net#38]
> Example chest radiography images of COVID-19 cases from 2 different patients and their associated critical factors (highlighted in red) as identified by GSInquire.

Can you kindly tell what is GSInquire and how it was instrumental in identifying associated critical factors?

**Comment by PaulMcInnis** [comment]
GSInquire is an explainability tool that highlights regions of interest associated with predictions. 

The image in README was produced with it. It is a GUI tool. 

It is currently available to medical practitioners to trial it as a way of assisting making informed decisions.

**Comment by paras-jain** [comment]
@PaulMcInnis, how can one get access to use it?

**Comment by PaulMcInnis** [comment]
From the README:
```If you are a researcher or healthcare worker and you would like access to the GSInquire tool to use to interpret COVID-Net results on your data or existing data, please reach out to a28wong@uwaterloo.ca or alex@darwinai.ca```

**Comment by paras-jain** [comment]
Thanks!
