### ISSUE TITLE
How to obtain the COVID-Netv2 model?

### ISSUE THREAD

**Issue by mmatheusmmiguel** [lindawangg/COVID-Net#43]
Hello my friends,

I'm trying to use train_tf to train with a pre-trained model, but it doesn't have this COVIDNetv2 file or model-2069. How to get them?

**Comment by lindawangg** [comment]
Please refer to the FAQ: https://github.com/lindawangg/COVID-Net/blob/master/docs/FAQ.md#where-are-the-covidnet-models
