### ISSUE TITLE
Can you please upload the ImageNet pretrained weights For COVID-Net?

### ISSUE THREAD

**Issue by Adamdad** [lindawangg/COVID-Net#44]
## Description

As mentioned in the paper, the COVID_Net has been pretrained on ImageNet. Could you please upload the imageNet pretrained weights so we can reproduce your result

**Comment by Electro1111** [comment]
I would also like this

**Comment by haydengunraj** [comment]
@Adamdad I added an answer to your question on @Electro1111 's recent issue, please see #92 for an answer.
