### ISSUE TITLE
Missing images from Figure1 dataset

### ISSUE THREAD

**Issue by fmobrj** [lindawangg/COVID-Net#47]
Thanks for the amazing work!

I see that in Covidx2 you used only 3 images from Figure1 collections. Is there a reason for that, or was it just timing? Do you know if there are overlaps between Figure1 and ieee8023/covid-chestxray-dataset?

**Comment by lindawangg** [comment]
That was just because of the timing of when the dataset was created. The data used from Figure1 are from sources that we know, so there's no overlap. We look at each data that comes from Figure1.
