### ISSUE TITLE
OSError: File models/COVIDNet-CXR-Large/model.meta does not exist

### ISSUE THREAD

**Issue by stu93303148** [lindawangg/COVID-Net#49]
How to fix it ?
<img width="1229" alt="螢幕快照 2020-04-22 下午6 26 49" src="https://user-images.githubusercontent.com/1113604/79971431-e181e980-84c6-11ea-8da2-7eb3e87ff2b2.png">

**Comment by lindawangg** [comment]
Refer to this FAQ: https://github.com/lindawangg/COVID-Net/blob/master/docs/FAQ.md#tried-running-the-scripts-but-says-that-model-doesnt-exist-how-to-get-them

**Comment by stu93303148** [comment]
OK thanks.
