### ISSUE TITLE
Missing checkpoint file

### ISSUE THREAD

**Issue by SuryaKalia** [lindawangg/COVID-Net#5]
Could you please include the checkpoint file which is missing in your Pretrained model (COVID-Netv1.zip)

On using a train saver, the following files might have been generated at your end:
- model.data-00000-of-00001
- model.meta
- model.index
- checkpoint

These 4 files would be required when importing the meta graph and restoring the latest checkpoint.

Thanks!

**Comment by Rhuax** [comment]
The checkpoint is the meta.index file.

**Comment by Vikramank** [comment]
this issue is discussed [here](https://github.com/lindawangg/COVID-Net/issues/2#issuecomment-605022714)
