### ISSUE TITLE
Visual result control

### ISSUE THREAD

**Issue by AlexandraAMC** [lindawangg/COVID-Net#51]
Hello everyone, 

I run the inference.py scipt on some "healthy" X ray images but the result was "Covid-19". I would like to check what the network is really classifing. 
I read in the joint paper that the QSInquire method was used to have a visual control of results. Is the method available ? Does someone know how it works ?
Or have an alternative way of visualise the result ? 

Thanks,

**Comment by haydengunraj** [comment]
Hi there,

You may request access to GSInquire to interpret COVID-Net results on your data or existing data, and contacts for this are listed in the [README file](https://github.com/lindawangg/COVID-Net/blob/master/README.md).

Alternatively, some users have tried Grad-CAM to visualize the network's predictions. If you want to go that route, have a look at #64 for a discussion of Grad-CAM as applied to COVID-Net.
