### ISSUE TITLE
Number of Trainable Parameters for COVID-Net

### ISSUE THREAD

**Issue by IamVNIE** [lindawangg/COVID-Net#52]
Any idea on the number of Trainable Parameters for COVID-Net CXR small and large?

The paper says the number of parameters in COVID-Net is 116.6 Million. However, keras network compiled in https://github.com/busyyang/COVID-19 which replicates the architecture in paper has 364.6 Million Parameters, which is more than 3 times the parameter.

**Comment by haydengunraj** [comment]
The numbers reported in the papers and in this repository are the source of truth for our models. Other implementations may construct the network differently and as such may differ in their parameter counts.
