### ISSUE TITLE
model-8485 vs model-10 (epoch 10)

### ISSUE THREAD

**Issue by homerdiaz** [lindawangg/COVID-Net#54]
Why the evaluation results are different when loading model-8485 and model-10 (epoch 10)?
These are my results when running eval.py using COVIDNet-CXR-Large, test_COVIDx2.txt and model-10 (epoch 10)

[[93.  7.  0.]
 [ 5. 93.  2.]
 [ 2.  2. 27.]]
Sens Normal: 0.930, Pneumonia: 0.930, COVID-19: 0.871
PPV Normal: 0.930, Pneumonia 0.912, COVID-19: 0.931

**Comment by haydengunraj** [comment]
Closing since this issue is almost a year old. For issues related to the current suite of models, a new issue should be opened.
