### ISSUE TITLE
Missing RSNA images

### ISSUE THREAD

**Issue by vakker** [lindawangg/COVID-Net#57]
RSNA has ~26k images, but COVIDx has ~13k samples.
Could you include some explanation on how the samples are chosen?

**Comment by lindawangg** [comment]
From the data script, https://github.com/lindawangg/COVID-Net/blob/master/create_COVIDx_v3.ipynb, the normal xrays were taken from one csv file and the pneumonia xrays were taken from another. The normal xrays were all label 'Normal' in the csv file and the pneumonia xrays were all labeled '1' in the other csv file. This is to eliminate the xrays that aren't normal and aren't pneumonia.
