### ISSUE TITLE
OSError: File models/COVIDNet-CXR-Small/model.meta_eval does not exist

### ISSUE THREAD

**Issue by stu93303148** [lindawangg/COVID-Net#59]
<img width="1129" alt="螢幕快照 2020-05-08 上午12 44 58" src="https://user-images.githubusercontent.com/1113604/81321663-77239880-90c5-11ea-9d23-0599479a6210.png">
How to fix it?

**Comment by haydengunraj** [comment]
You'll need to download the meta and weights for COVIDNet-CXR-Small from [here](https://github.com/lindawangg/COVID-Net/blob/master/docs/models.md). After downloading, you should set the command line arguments `--weightspath /path/to/model/directory` and `--metaname model.meta`.
