### ISSUE TITLE
Script for loading the model

### ISSUE THREAD

**Issue by ALI7861111** [lindawangg/COVID-Net#7]
is:issue  Sir can you provide a simple code to load the model because i have tried many methods and all are showing some errors kindly also mention versions of tf. last error i got was :
 {module 'tensorflow._api.v2.train' has no attribute 'import_meta_graph')    
 ............... the code was as following :
 import tensorflow as tf 
new_graph = tf.Graph()
 with tf.compat.v1.Session(graph=new_graph) as sess:      
        saver = tf.train.import_meta_graph('/content/models2/model.meta')       
       saver.restore(sess, "/content/models2/model")

i have also tried  tf.compat.v1.Session and tf.Session but unable to load the model

**Comment by josephius** [comment]
You're actually quite close.  Just change the following:

> `tf.train.import_meta_graph`

To:  `tf.compat.v1.train.import_meta_graph`

**Comment by lindawangg** [comment]
We just released the [evaluation script](eval.py) with the new model. Loading the model can be found in there.

**Comment by ALI7861111** [comment]
thanks a lot

**Comment by ALI7861111** [comment]
> We just released the [evaluation script](https://github.com/lindawangg/COVID-Net/blob/master/eval.py) with the new model. Loading the model can be found in there.

Can i get a script to like predict a single image the code is quite messy and no comments are made in it.  Like i want to predict a single image on the model

**Comment by ALI7861111** [comment]
> is:issue Sir can you provide a simple code to load the model because i have tried many methods and all are showing some errors kindly also mention versions of tf. last error i got was :
> {module 'tensorflow._api.v2.train' has no attribute 'import_meta_graph')
> ............... the code was as following :
> import tensorflow as tf
> new_graph = tf.Graph()
> with tf.compat.v1.Session(graph=new_graph) as sess:
> saver = tf.train.import_meta_graph('/content/models2/model.meta')
> saver.restore(sess, "/content/models2/model")
> 
> i have also tried tf.compat.v1.Session and tf.Session but unable to load the model

Thanks that worked :)
