### ISSUE TITLE
New dataset released about 1k covid positive, and 1k covid-negative (suggestion)

### ISSUE THREAD

**Issue by JordanMicahBennett** [lindawangg/COVID-Net#71]
I suggest usage of [dataset released May 14, 2020](https://www.kaggle.com/plameneduardo/sarscov2-ctscan-dataset), via Angelov Et al:

Dataset details:

- 1252 CT scans for covid19 positive
- 1230 CT scans for non-covid19 
- 2482 Total

**Comment by lindawangg** [comment]
Thanks for the info. I'll forward this to @haydengunraj as he's been working with CTs.
