### ISSUE TITLE
using your image from study gives false positive?

### ISSUE THREAD

**Issue by jomollin** [lindawangg/COVID-Net#77]
Hallo,
I used image A from your study, just a screen shot, and got it as covid-19 for 99.9 %
Maybe you can send me the original image for testing

How that?

**Comment by lindawangg** [comment]
I'm not sure exactly which image that is but it's a non-COVID19 infection from this dataset: https://github.com/ieee8023/covid-chestxray-dataset. Having that image classified as covid-19 is totally possible as the models don't have a 100% positive predictive value.

**Comment by jomollin** [comment]
I'm checking additionally some images from https://github.com/agchung/Actualmed-COVID-chestxray-dataset which are marked with no finding, but always comes back to me as covid positive

**Comment by Apekshagaonkar** [comment]
Hello,
Even I have the same issue.
I tried to inference images from dataset you have used to train.
https://www.kaggle.com/tawsifurrahman/covid19-radiography-database
It shows covid positive to even normal and pneumonia case.
Can you let us know if we have to do any preprocessing other than mentioned in your repository.

**Comment by palatos** [comment]
I'd like to second the request of the users above. I loaded the "COVIDNet-CXR3-C" and tried a bunch of normal (no illness) images from the datasets that go into COVIDx, and I'm always getting ~0.99 softmax output for the COVID-19 class.
I'm not sure if it's a problem with loading the models or something with the preprocessing of the image.

It'd be nice to confirm.

**Comment by haydengunraj** [comment]
Closing this issue now. For any related problems with the more recent models, please open a new issue.
