### ISSUE TITLE
how to inference the other models?

### ISSUE THREAD

**Issue by jomollin** [lindawangg/COVID-Net#80]
model COVIDNet-CXR3-B for inference works fine like in die example

how is the cli for the other models?

**Comment by lindawangg** [comment]
To inference the other files it's the same as the command for model B, but with different weightpath and ckptname, like below.
```
python inference.py \
    --weightspath models/COVIDNet-CXR3-X \
    --metaname model.meta \
    --ckptname model-XXXX \
    --imagepath assets/ex-covid.jpeg```
