### ISSUE TITLE
Labeling the data?

### ISSUE THREAD

**Issue by stunbomb** [lindawangg/COVID-Net#81]
How did you label the data for your model? Does the github include a program that will label the data?

**Comment by lindawangg** [comment]
The data came from different sources, and to my knowledge, they were all labeled by radiologists.

**Comment by stunbomb** [comment]
> The data came from different sources, and to my knowledge, they were all labeled by radiologists.

only the images from Figure1-COVID-chestxray-dataset are labeled the others are not.
