### ISSUE TITLE
Convert to Keras Model

### ISSUE THREAD

**Issue by ammarchalifah** [lindawangg/COVID-Net#82]
First I want to say thank you for this amazing model. I'm interested to study more and tweak some parameters in the model and experimenting myself, and the model is saved with meta, ckpt, and index format. It can be loaded with the classical tensorflow graph and session. Personally, I haven't learn much on session and graph in TF and prefer to tweak the model with keras functional API. is there any reference/solution to import the model weight and architecture to a keras model? Thanks in advance

**Comment by lindawangg** [comment]
I'm not sure how to load in a tensorflow graph and train it using keras, but you can refer to this branch: https://github.com/lindawangg/COVID-Net/tree/covidnet-keras. It hasn't been updated in a while but has the training scripts we used at the very beginning.

**Comment by ammarchalifah** [comment]
That's okay. It solved my issue, thanks a lot.
