### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by kojix2** [lindawangg/COVID-Net#84]
Hi, thanks for a great project.

To make it easier for clinicians to try this project, I have created a dockerfile. 
* https://github.com/kojix2/covid-net-docker
* https://hub.docker.com/repository/docker/kojix2/covid-net

This will automatically download your pre-trained data from Google drive by using [gdown](https://github.com/wkentaro/gdown).

I'm also a physician and although I don't currently work in a clinical setting, I'm trying to figure out if there's a way to actually make projects like this useful to the world in the midst of global pandemic. 
I would like to investigate whether this project would be useful in a hospital. 
(Yes, I understand that this project is not a production-ready solution, and creators of this project do not take any responsibility for using it.)

I like open source.

Keep up the good work!!

**Comment by neurahealth** [comment]
@kojix2 We have made COVID-Net easily accessible to clinicians by building NeuraCovid. See details here: https://github.com/lindawangg/COVID-Net/issues/69
Also, NeuraCovid is open sourced.

**Comment by kojix2** [comment]
Updated to use a multi-stage build.
This shortens the build time.
