### ISSUE TITLE
I have this error. FileNotFoundError: [Errno 2] No such file or directory: 'train_split_v3.txt' can somebody help me?

### ISSUE THREAD

**Issue by AI-P-K** [lindawangg/COVID-Net#87]
# Issue Template
Before posting, have you looked at the [FAQ](../docs/FAQ.md) page?

## Description

Please include a summary of the issue.
Please include the steps to reproduce.
List any additional libraries that are affected.

## Steps to Reproduce

1. First step
2. Second step
3. Third step

## Expected behavior

A description of what you expected to happen.

## Actual behavior

A description of what happens instead.

## Environment

* Build: [e.g. 3180 - type "About" in the Command Palette]
* Operating system and version: [e.g. macOS 10.14, Windows 10, Ubuntu 18.04]
* [Linux] Desktop Environment and/or Window Manager: [e.g. Gnome, LXDE, i3]

**Comment by haydengunraj** [comment]
My assumption is that you got this error when running `train_tf.py` with the argument `--trainfile train_split_v3.txt`. This file is now named `train_COVIDx3.txt`, so passing `--trainfile train_COVIDx3.txt` should resolve the issue.

**Comment by haydengunraj** [comment]
Closing since it appears the issue was resolved.
