### ISSUE TITLE
Example of how to use the pre-trained model

### ISSUE THREAD

**Issue by jjmaestro** [lindawangg/COVID-Net#9]
I've managed to load the provided model, but I'm not sure how to proceed from there to actually use it on an image.

In #2 @vikramank mentioned a Flask app, so I assume it's possible to use the pre-trained models, but without more info or docs, I don't know how to do it.

EDIT: actually, digging a bit more into this, it seems that, without the actual Keras model, using the Tensorflow checkpoint is pretty hard :-? From https://github.com/keras-team/keras/issues/5273#issuecomment-296000000:

> Fundamentally, you cannot "turn an arbitrary TensorFlow checkpoint into a Keras model".
> 
> What you can do, however, is build an equivalent Keras model then load into this Keras model the weights contained in a TensorFlow checkpoint that corresponds to the saved model. In fact this is how the pre-trained InceptionV3 in Keras was obtained.

So, without more info, it seems pretty hard (or impossible?) to do :-?

Would it be possible to add a simple example script that (1) gets the path to an image as input (1) loads the module (2) uses it and outputs the "COVID probability"?

Thanks!

**Comment by lindawangg** [comment]
We just released the [evaluation script](https://github.com/lindawangg/COVID-Net/blob/master/eval.py), which loads in the provided model and then runs inference to get the predicted class.

**Comment by lindawangg** [comment]
We just released an [inference script](https://github.com/lindawangg/COVID-Net/blob/master/inference.py) today that takes the path of the model and image and outputs a prediction.

**Comment by jjmaestro** [comment]
Great, thanks! Those are what I was looking for. I'll give them a try!
