### ISSUE TITLE
Sensitivity / Specificity

### ISSUE THREAD

**Issue by jomollin** [lindawangg/COVID-Net#91]
Hi Linda,

is your named Positive Predictive Value (%) identical to Specificity in your different models?

Best 
Joachim

**Comment by haydengunraj** [comment]
Hi Joachim,

Specificity and PPV are different measures. Specificity measures the proportion of ground-truth negatives which were correctly predicted negative (i.e., sens = TN/(FP + TN)), whereas PPV measures the proportion of positive predictions which are true positives (i.e., PPV = TP/(TP + FP)).
